# Generated by Django 3.2.7 on 2021-09-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(blank=True, choices=[('PGC', 'PGC'), ('PF', 'PF'), ('APLS', 'APLS')], max_length=50, null=True)),
                ('rayon', models.CharField(blank=True, choices=[('Rayon Epiceries', 'Rayon Epiceries'), ('Rayon Confiserie Biscuterie', 'Rayon Confiserie Biscuterie'), ('Rayon Liquide', 'Rayon Liquide'), ('Rayon Droguerie Parfumerie Hygiène', 'Rayon Droguerie Parfumerie Hygiène'), ('', '')], max_length=50, null=True)),
                ('code_fournisseur', models.CharField(max_length=14, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default='0', null=True)),
                ('expire_date', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
