# Generated by Django 3.2.7 on 2021-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code_fournisseur',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
