# Generated by Django 3.2.7 on 2021-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_code_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
