# Generated by Django 3.2.7 on 2021-09-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stock', '0003_alter_stock_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('poste', models.CharField(choices=[('Chef de département', 'Chef de département'), ('Chef de rayon', 'Chef de rayon'), ('Assistante de département', 'Assistante de département'), ('Responsable réception marchandise', 'Responsable réception marchandise')], max_length=50)),
                ('departement', models.CharField(choices=[('PGC', 'PGC'), ('PF', 'PF'), ('APLS', 'APLS')], max_length=15)),
            ],
        ),
    ]
