# Generated by Django 3.2.7 on 2021-09-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='rayon',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
