# Generated by Django 3.2.7 on 2021-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stock_rayon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='rayon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
