# Generated by Django 3.2.7 on 2021-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stock_rayon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='rayon',
            field=models.CharField(blank=True, choices=[('PGC_Rayon_CHOICES', 'PGC_Rayon_CHOICES'), ('Marche_Rayon_CHOICES', 'Marche_Rayon_CHOICES'), ('APLS_Rayon_CHOICES', 'APLS_Rayon_CHOICES')], max_length=50, null=True),
        ),
    ]
